const { google } = require('googleapis');
const { getOrCreateLabel, addLabel } = require('./labelController');

const getUnreadMessages = async (auth) => {
    const gmail = google.gmail({ version: "v1", auth });

    //finding unread messages
    const response = await gmail.users.messages.list({
        userId: "me",
        q: "is:unread",
        labelIds: ["INBOX"],
    });

    //return msgs or empty array
    return response.data.messages || [];
};


const sendReply = async (auth, msgs) => {
    if (msgs && msgs.length > 0) {
        for (const msg of msgs) {
            const gmail = google.gmail({ version: "v1", auth });
            const mail = await gmail.users.messages.get({
                userId: "me",
                id: msg.id,
            })

            // const obj = JSON.stringify(mail.data, null, 2);
            // console.log(obj);
            // console.log(mail.data.payload.headers);

            const { value: subject } = mail.data.payload.headers.find(
                (obj) => obj.name.toLowerCase() === "subject"
            )

            const { value: from } = mail.data.payload.headers.find(
                (obj) => obj.name.toLowerCase() === "from"
            )
            // To will always be "me"

            const thread = await gmail.users.threads.get({
                userId: "me",
                id: msg.threadId,
            })
            const replies = thread.data.messages.slice(1);

            // console.log(replies);
            const replyBody =
                "Hi there,\nI am currently not available. This is an autogenerated mail.\nWill get back to you soon.";

            if (replies.length === 0) {
                await gmail.users.messages.send({
                    userId: "me",
                    requestBody: {
                        raw: Buffer.from(
                            `From: "me"\nTo: ${from}\nSubject: ${subject}\n\n${replyBody}`
                        ).toString("base64"),
                        threadId: msg.id,
                    },
                })
            } else {
                console.log("No unread threads")
            }

            const labelId = await getOrCreateLabel(auth);
            await addLabel(auth, labelId, msg.id);


            console.log(`Sent reply to: ${from}`)

        }
    } else {
        console.log("No new messages")
    }
}

module.exports = { getUnreadMessages, sendReply }